spring.application.name=backend
#change This to your Database credentials
#if you wanna use environment variables check out this article:
#https://www.baeldung.com/spring-boot-properties-env-variables
spring.datasource.url=${DB_URL}

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.SQL=DEBUG


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#jwt keys
#To generate your secret key run:
#openssl rand -base64 32
# It should look something like this:
# TIGzpevixRVpMpbTWT2l6CB+tMMDBDB2lZ69ZYIp4vry2AKZj3EQhgQJ5C3KOIyfjUbyNkHPd0+DIc.
#Note: Ensure there are no breaks in the key (e.g., white spaces, line breaks).
app.jwt.secret=${JWT_SECRET}
